version: '3.8'

services:
  app:
    image: hykilpikonna/aquadx:latest
    ports:
      - "80:80"
      - "8443:8443"
      - "22345:22345"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/main
      - SPRING_DATASOURCE_USERNAME=cat
      - SPRING_DATASOURCE_PASSWORD=meow
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
    depends_on:
      - db
    volumes:
      - aqua_config:/app/config
      - aqua_data:/app/data
    entrypoint: ["/bin/sh", "-c"]
    command: ["ls -la /app/config]

  db:
    image: mariadb:10.8.2
    environment:
      MYSQL_ROOT_PASSWORD: meow
      MYSQL_DATABASE: main
      MYSQL_USER: cat
      MYSQL_PASSWORD: meow
    ports:
      - "127.0.0.1:3369:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
  aqua_config:
  aqua_data:
